(function(){if(window.ARC&&window.ARC.Tools&&window.ARC.Tools.logger)return;window.ARC=window.ARC||{};window.ARC.Tools=window.ARC.Tools||{};var T=ARC.Tools;var i=0;var location=document.location.toString();if(!Date.now)Date.now=function now(){return(new Date).getTime()};var start=Date.now();T.Time={start:function(){return start},elapsed:function(){return Date.now()-start},toHuman:function(milli){if(milli<1E3)return milli+"ms";var string="";var remain=milli;var ms=remain%1E3;remain=(remain-ms)/1E3;
if(ms<10)ms="00"+ms;else if(ms<100)ms="0"+ms;var s=remain%60;remain=(remain-s)/60;string=s+"."+ms+"s";if(remain===0)return string;var min=remain%60;remain=(remain-min)/60;string=min+(min>1?" minutes ":" minute ")+string;if(remain===0)return string;var h=remain%24;remain=(remain-h)/24;string=h+(h>1?" hours ":" hour ")+string;if(remain===0)return string;var d=remain;string=d+(d>1?" days ":" day ")+string;return string}};var origConsole=window.console;var useConsole=!!location.match(/console=all/);var loggers=
[];function logger(namespace){if(!namespace||namespace==="")namespace="DEFAULT";var counter=0;var newname=namespace;while(loggers[newname]){counter=counter+1;newname=namespace+"_"+counter}this.namespace=newname;loggers[newname]=this;this.groupLevel=0;this.messages=[]}logger.prototype.originalConsole=origConsole;logger.prototype.loggers=function(){return loggers};logger.prototype.forceLogging=function(){useConsole=true};logger.prototype.forceStartTime=function(time){start=time};ARC.Tools.logger=logger;
function writelog(that,method,args){var argsArray=[];var savedArray=[];for(var i=0;i<args.length;i++){argsArray.push(args[i]);savedArray.push(args[i])}if(method.match(/^(log|info|warn|error|debug|trace|_exception)$/))if(argsArray.length>=2&&typeof argsArray[argsArray.length-1]=="function"){that.group.apply(that,argsArray.slice(0,argsArray.length-1));argsArray[argsArray.length-1]();that.groupEnd();return}argsArray.unshift("["+that.namespace+"]");var padding="";for(i=0;i<that.groupLevel;i++)padding=
padding+"    ";argsArray.unshift(padding);savedArray.unshift(padding);argsArray.push("("+T.Time.toHuman(T.Time.elapsed())+")");savedArray.push("("+T.Time.toHuman(T.Time.elapsed())+")");var forceConsole=window.localStorage&&window.localStorage.getItem&&(window.localStorage.getItem("console-show-"+that.namespace)||window.localStorage.getItem("console-show-"+that.namespace.toLowerCase()));var nameRegex=new RegExp("[?\x26]console\x3d"+that.namespace,"i");forceConsole=forceConsole||location.match(nameRegex);
var allString=true;for(i=0;i<argsArray.length;i++)if(typeof argsArray[i]!="string")allString=false;if(allString)argsArray=[argsArray.join(" ")];if((useConsole||forceConsole)&&origConsole&&origConsole[method])if(method=="group")try{origConsole.log.apply(origConsole,argsArray)}catch(e){origConsole.log(argsArray)}else try{origConsole[method].apply(origConsole,argsArray)}catch(e){origConsole[method](argsArray)}var flattened="";for(i=0;i<savedArray.length;i++)if(savedArray[i]===null)savedArray[i]="null";
else if(typeof savedArray[i]=="undefined")savedArray[i]="undefined";else savedArray[i]=savedArray[i].toString();that.messages.push(savedArray.join(" "));if(that.messages.length>100)that.messages.splice(0,1)}logger.prototype.text=function(){return this.messages.join("\n")};logger.prototype.getMessages=function(namespace){if(origConsole&&loggers[namespace])origConsole.log(loggers[namespace].text())};var logMethods=["log","info","warn","error","debug","trace","_exception"];function _logMethodsHelper(method){return function(){writelog(this,
method,arguments)}}for(i=0;i<logMethods.length;i++)logger.prototype[logMethods[i]]=_logMethodsHelper(logMethods[i]);logger.prototype.group=function(){writelog(this,"group",arguments);this.groupLevel=this.groupLevel+1};logger.prototype.groupEnd=function(){this.groupLevel=this.groupLevel-1};logger.prototype.groupCollapsed=logger.prototype.group;var otherMethods=["assert","count","dir","dirxml","table","time","timeEnd","timeStamp","profile","profileEnd"];function _otherMethodsHelper(method){return function(){if(useConsole&&
origConsole&&origConsole[method])try{origConsole[method].apply(origConsole,arguments)}catch(e){originalConsole[method](arguments)}}}for(i=0;i<otherMethods.length;i++)logger.prototype[otherMethods[i]]=_otherMethodsHelper(otherMethods[i]);if(!location.match(/[?&]console=orig/))window.console=new T.logger})();
(function(){if(window.ARC&&window.ARC.Tools&&window.ARC.Tools.timedToken)return;window.ARC=window.ARC||{};window.ARC.Tools=window.ARC.Tools||{};ARC.Tools.timedToken=function(config){var config=config||{unit:"minute",increment:1},unit=config.unit.slice(-1)=="s"?config.unit.slice(0,-1):config.unit,increment=config.increment,numberOfSeconds={"second":1,"minute":60,"hour":3600,"day":86400},date=new Date;var coeff=1E3*numberOfSeconds[unit]*increment;var rounded=(new Date(Math.round(date.getTime()/coeff)*
coeff)).getTime();return rounded}})();mvtTracking={};mvtPromise=$.Deferred();navCollapsedCookie="nav_collapsed";navigationReadyEvent="NAVIGATION_READY";_dw=window._dw||[];_dw.push(["global","before",function(api){api.segment("wide-screen",isWideScreenSegment);api.dispatch("segments-done")}]);_dw.push(["global","ready",function(api){var variant=api.get("Navigation-collapsible");mvtPromise.resolve(variant)}]);function isWideScreenSegment(){return window.innerWidth>=1269}
function parseQueryString(){var url=window.location.href;var urlParams={};url.replace(new RegExp("([^?\x3d\x26]+)(\x3d([^\x26]*))?","g"),function($0,$1,$2,$3){urlParams[$1]=$3});return urlParams}$(window).on(navigationReadyEvent,function(){mvtPromise.done(function(variant){mvtNavigation.init(variant)})});
mvtNavigation={init:function(variant){if(isWideScreenSegment()){var navTrackVar=variant.getTrackVar();if(navTrackVar.length!=0){var navCollapsible=variant.is("true")?"true":variant.is("false")?"false":"default";var navVariantHash=navTrackVar.match("-[a-z0-9]+$")[0];navTrackVar=navTrackVar.replace(",","|").toLowerCase();var navState="default";navCollapsedCookie+=navVariantHash;var params=parseQueryString();if(params.hasOwnProperty("nav_collapsible"))navCollapsible=["true","false"].indexOf(params.nav_collapsible)>
-1?params.nav_collapsible:navCollapsible;if(navCollapsible=="true"){navState=getCookie(navCollapsedCookie)=="true"?"closed":getCookie(navCollapsedCookie)=="false"?"open":"open";this.initCollapsible();this.setCollapsibleState(navState)}mvtTracking["multivartiant_variant"]=navTrackVar;mvtTracking["multivartiant_state"]=navState}}},initCollapsible:function(){var body=$("body");body.addClass("nav-collapsible")},setCollapsibleState:function(state){var body=$("body");var nav=$("#nav");var navToggle=$("#nav-toggle");
if(state=="open"){body.removeClass("nav-collapsed");nav.removeClass("compressed");nav.addClass("expanded");navToggle.removeClass("open-nav");navToggle.addClass("close-nav")}else if(state=="closed"){body.addClass("nav-collapsed");nav.addClass("compressed");nav.removeClass("expanded");navToggle.addClass("open-nav");navToggle.removeClass("close-nav");body.addClass("fade-in");nav.addClass("fade-in");setTimeout(function(){body.removeClass("fade-in");nav.removeClass("fade-in")},450)}navToggle.on("click",
function(){if($(this).hasClass("open-nav"))cs.customTrack({"navigation_action":"open"});else if($(this).hasClass("close-nav"))cs.customTrack({"navigation_action":"close"})})}};